# Generated by Django 5.2.8 on 2025-11-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_garage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('letter_note', models.TextField(blank=True, null=True)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('date_of_clearing', models.CharField(max_length=255)),
                ('fact_gst_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(default='FACTOMFOS', max_length=255)),
                ('hsn_sac_code', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('is_garage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_km', models.FloatField()),
                ('to_km', models.FloatField()),
                ('rate', models.FloatField()),
                ('is_mtk', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_note', models.TextField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(max_length=255)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.destination')),
                ('main_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.mainbill')),
            ],
        ),
        migrations.CreateModel(
            name='MainBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.destinationentry')),
                ('main_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.mainbill')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.destination')),
                ('places', models.ManyToManyField(related_name='dealers', to='erp.place')),
            ],
        ),
        migrations.CreateModel(
            name='RangeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('total_bags', models.IntegerField(blank=True, null=True)),
                ('total_mt', models.FloatField(blank=True, null=True)),
                ('total_mtk', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('destination_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.destinationentry')),
                ('rate_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.raterange')),
            ],
        ),
        migrations.CreateModel(
            name='DealerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('despatched_to', models.CharField(blank=True, max_length=255, null=True)),
                ('km', models.FloatField(blank=True, null=True)),
                ('no_bags', models.IntegerField()),
                ('rate', models.FloatField()),
                ('mt', models.FloatField()),
                ('mtk', models.FloatField()),
                ('amount', models.FloatField()),
                ('mda_number', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('description', models.CharField(default='FACTOM FOS', max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.dealer')),
                ('range_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.rangeentry')),
            ],
        ),
    ]
