# Generated by Django 5.2.8 on 2026-02-24 10:30

import django.db.models.deletion
import erp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_garage', models.BooleanField(default=False)),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RateRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_km', models.FloatField()),
                ('to_km', models.FloatField()),
                ('rate', models.FloatField()),
                ('is_mtk', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('letter_note', models.TextField(blank=True, null=True)),
                ('date_of_clearing', models.CharField(max_length=255)),
                ('product', models.CharField(default='FACTOMFOS', max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DestinationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_note', models.TextField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(max_length=255)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('transport_type', models.CharField(blank=True, choices=[('TRANSPORT_DEPOT', 'Transport Depot'), ('TRANSPORT_FOL', 'Transport FOL')], max_length=20, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.destination')),
                ('service_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_entries', to='erp.servicebill')),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='erp.destination')),
            ],
            options={
                'unique_together': {('name', 'destination')},
            },
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('places', models.ManyToManyField(related_name='dealers', to='erp.place')),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RangeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.FloatField()),
                ('total_bags', models.IntegerField(blank=True, null=True)),
                ('total_mt', models.FloatField(blank=True, null=True)),
                ('total_mtk', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('is_transport_fol_slab', models.BooleanField(default=False)),
                ('print_page_no', models.IntegerField(blank=True, null=True)),
                ('destination_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_entries', to='erp.destinationentry')),
                ('rate_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.raterange')),
                ('service_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_entries', to='erp.servicebill')),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HandlingBillSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('qty_shipped', models.FloatField(blank=True, null=True)),
                ('fol_total', models.FloatField(blank=True, null=True)),
                ('depot_total', models.FloatField(blank=True, null=True)),
                ('rh_sales', models.FloatField(blank=True, null=True)),
                ('qty_received', models.FloatField(blank=True, null=True)),
                ('shortage', models.FloatField(blank=True, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
                ('total_qty', models.FloatField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('bill_amount', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('total_bill_amount', models.FloatField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handling', to='erp.servicebill')),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DealerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('despatched_to', models.CharField(blank=True, max_length=255, null=True)),
                ('km', models.FloatField(blank=True, null=True)),
                ('no_bags', models.IntegerField()),
                ('rate', models.FloatField()),
                ('mt', models.FloatField()),
                ('mtk', models.FloatField()),
                ('amount', models.FloatField()),
                ('mda_number', models.CharField(max_length=255)),
                ('bill_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(max_length=255)),
                ('description', models.CharField(default='FACTOM FOS', max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.dealer')),
                ('range_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_entries', to='erp.rangeentry')),
                ('service_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_entries', to='erp.servicebill')),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransportDepotSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('total_depot_qty', models.FloatField(blank=True, null=True)),
                ('total_depot_amount', models.FloatField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_depot', to='erp.servicebill')),
            ],
        ),
        migrations.CreateModel(
            name='TransportDepotRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=255)),
                ('qty_mt', models.FloatField()),
                ('km', models.FloatField()),
                ('mt_km', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.destination')),
                ('range_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='erp.rangeentry')),
                ('depot_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='erp.transportdepotsection')),
            ],
        ),
        migrations.CreateModel(
            name='TransportFOLSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('rh_qty', models.FloatField(default=0)),
                ('grand_total_qty', models.FloatField(default=0)),
                ('grand_total_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fol', to='erp.servicebill')),
            ],
        ),
        migrations.CreateModel(
            name='TransportFOLSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_slab', models.CharField(blank=True, max_length=50)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('range_total_qty', models.FloatField(blank=True, null=True)),
                ('range_total_mtk', models.FloatField(blank=True, null=True)),
                ('range_total_amount', models.FloatField(blank=True, null=True)),
                ('fol_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='erp.transportfolsection')),
            ],
            options={
                'unique_together': {('fol_section', 'range_slab')},
            },
        ),
        migrations.CreateModel(
            name='TransportFOLDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_place', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_mt', models.FloatField()),
                ('qty_mtk', models.FloatField()),
                ('amount', models.FloatField()),
                ('destination_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_fol_destinations', to='erp.destinationentry')),
                ('fol_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='erp.transportfolslab')),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name='rangeentry',
            name='fol_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_entries', to='erp.transportfolslab'),
        ),
    ]
