# Generated by Django 5.2.8 on 2025-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
