# Generated by Django 5.2.8 on 2026-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_dealer_created_at_dealer_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebill',
            name='date_of_clearing',
            field=models.DateField(blank=True, null=True),
        ),
    ]
