# Generated by Django 5.2.8 on 2025-11-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_place_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='erp.destination'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'destination')},
        ),
    ]
