# Generated by Django 5.2.8 on 2025-11-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_place_destination_alter_place_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='destination',
        ),
        migrations.AddField(
            model_name='dealer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
