# Generated by Django 5.2.8 on 2025-12-02 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_dealer_destination_dealer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeentry',
            name='destination_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='erp.destinationentry'),
        ),
    ]
