# Generated by Django 5.2.8 on 2025-12-02 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_rangeentry_destination_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerentry',
            name='range_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_entries', to='erp.rangeentry'),
        ),
        migrations.AlterField(
            model_name='rangeentry',
            name='destination_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_entries', to='erp.destinationentry'),
        ),
    ]
