# Generated by Django 5.2.8 on 2025-12-16 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_alter_dealerentry_range_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('letter_note', models.TextField(blank=True, null=True)),
                ('date_of_clearing', models.CharField(max_length=255)),
                ('product', models.CharField(default='FACTOMFOS', max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destinationentry',
            name='main_bill',
        ),
        migrations.RemoveField(
            model_name='mainbillentry',
            name='main_bill',
        ),
        migrations.RemoveField(
            model_name='mainbillentry',
            name='destination_entry',
        ),
        migrations.AddField(
            model_name='destinationentry',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('TRANSPORT_DEPOT', 'Transport Depot'), ('TRANSPORT_FOL', 'Transport FOL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rangeentry',
            name='is_transport_fol_slab',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HandlingBillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('qty_shipped', models.FloatField(blank=True, null=True)),
                ('fol_total', models.FloatField(blank=True, null=True)),
                ('depot_total', models.FloatField(blank=True, null=True)),
                ('rh_sales', models.FloatField(blank=True, null=True)),
                ('qty_received', models.FloatField(blank=True, null=True)),
                ('shortage', models.FloatField(blank=True, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
                ('total_qty', models.FloatField(blank=True, null=True)),
                ('bill_amount', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('total_bill_amount', models.FloatField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handling', to='erp.servicebill')),
            ],
        ),
        migrations.AddField(
            model_name='destinationentry',
            name='service_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_entries', to='erp.servicebill'),
        ),
        migrations.CreateModel(
            name='TransportDepotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('total_depot_qty', models.FloatField(blank=True, null=True)),
                ('total_depot_amount', models.FloatField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_depot', to='erp.servicebill')),
            ],
        ),
        migrations.CreateModel(
            name='TransportFOLSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=255, unique=True)),
                ('rh_qty', models.FloatField(blank=True, null=True)),
                ('total_fol_qty', models.FloatField(blank=True, null=True)),
                ('total_fol_amount', models.FloatField(blank=True, null=True)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fol', to='erp.servicebill')),
            ],
        ),
        migrations.CreateModel(
            name='TransportFOLSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.FloatField()),
                ('total_mtk', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('fol_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='erp.transportfolsection')),
                ('slab_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.raterange')),
            ],
        ),
        migrations.AddField(
            model_name='rangeentry',
            name='fol_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_entries', to='erp.transportfolslab'),
        ),
        migrations.DeleteModel(
            name='MainBill',
        ),
        migrations.DeleteModel(
            name='MainBillEntry',
        ),
    ]
