# Generated by Django 5.2.8 on 2025-12-24 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_servicebill_remove_destinationentry_main_bill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportfolslab',
            old_name='total_mtk',
            new_name='range_total_amount',
        ),
        migrations.RemoveField(
            model_name='transportfolsection',
            name='total_fol_amount',
        ),
        migrations.RemoveField(
            model_name='transportfolsection',
            name='total_fol_qty',
        ),
        migrations.RemoveField(
            model_name='transportfolslab',
            name='slab_range',
        ),
        migrations.RemoveField(
            model_name='transportfolslab',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transportfolslab',
            name='total_qty',
        ),
        migrations.AddField(
            model_name='transportfolsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportfolsection',
            name='grand_total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportfolsection',
            name='grand_total_qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transportfolsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transportfolslab',
            name='range_slab',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transportfolslab',
            name='range_total_mtk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportfolslab',
            name='range_total_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportfolslab',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportfolsection',
            name='rh_qty',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='TransportFOLDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_place', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_mt', models.FloatField()),
                ('qty_mtk', models.FloatField()),
                ('amount', models.FloatField()),
                ('fol_slab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='erp.transportfolslab')),
            ],
        ),
    ]
