# Generated by Django 5.2.8 on 2025-12-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rename_total_mtk_transportfolslab_range_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transportfolslab',
            unique_together={('fol_section', 'range_slab')},
        ),
    ]
