# Generated by Django 5.2.8 on 2025-12-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_transportfolslab_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerentry',
            name='service_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_entries', to='erp.servicebill'),
        ),
    ]
