# Generated by Django 5.2.8 on 2025-12-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_dealerentry_service_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportfoldestination',
            name='destination_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_fol_destinations', to='erp.destinationentry'),
        ),
    ]
