# Generated by Django 5.2.8 on 2026-01-27 14:29

from django.db import migrations, models

def dedupe_and_uppercase_places(apps, schema_editor):
    Place = apps.get_model("erp", "Place")

    # Step 1: group by (UPPER(name), destination_id)
    groups = {}

    for place in Place.objects.all():
        key = (place.name.upper().strip(), place.destination_id)
        groups.setdefault(key, []).append(place)

    # Step 2: process each group
    for (name_uc, dest_id), places in groups.items():
        canonical = places[0]

        # merge duplicates
        for dup in places[1:]:
            # move M2M dealers
            canonical.dealers.add(*dup.dealers.all())
            dup.delete()

        # now it's safe to update canonical
        canonical.name = name_uc
        if canonical.district:
            canonical.district = canonical.district.upper()

        canonical.save()


def uppercase_existing_data(apps, schema_editor):
    def process_model(model_name, exclude_fields=None, force_include=None):
        exclude_fields = exclude_fields or []
        force_include = force_include or []

        Model = apps.get_model("erp", model_name)

        for obj in Model.objects.all():
            changed = False

            for field in obj._meta.fields:
                name = field.name

                # explicitly included fields
                if name in force_include:
                    val = getattr(obj, name, None)
                    if isinstance(val, str):
                        setattr(obj, name, val.upper())
                        changed = True
                    continue

                # excluded fields
                if name in exclude_fields:
                    continue

                if isinstance(field, (models.CharField, models.TextField)):
                    val = getattr(obj, name, None)
                    if isinstance(val, str):
                        setattr(obj, name, val.upper())
                        changed = True

            if changed:
                obj.save(update_fields=None)

    # === MODELS ===

    process_model(
        "Destination",
        exclude_fields=["description"],
    )
    
    dedupe_and_uppercase_places(apps, schema_editor)


    process_model(
        "Dealer"
    )

    process_model(
        "DestinationEntry",
        exclude_fields=["letter_note"],
    )

    process_model(
        "RangeEntry"
    )

    process_model(
        "DealerEntry",
        exclude_fields=["remarks"],
        force_include=["description"],
    )

    process_model(
        "ServiceBill",
        exclude_fields=["letter_note"],
    )

    process_model(
        "HandlingBillSection"
    )

    process_model(
        "TransportDepotSection"
    )

    process_model(
        "TransportFOLSection"
    )

    process_model(
        "TransportFOLSlab"
    )

    process_model(
        "TransportFOLDestination"
    )


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('erp', '0011_transportfoldestination_destination_entry'),
    ]


    operations = [
        migrations.RunPython(uppercase_existing_data),
    ]
