# Generated by Django 5.2.8 on 2026-01-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_uppercase_existing_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeentry',
            name='print_page_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
