# Generated by Django 5.2.8 on 2026-01-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_rangeentry_print_page_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerentry',
            name='bill_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
