# Generated by Django 5.2.8 on 2026-02-11 12:51

import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_dealerentry_bill_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(erp.models.UppercaseMixin, models.Model),
        ),
    ]
