# Generated by Django 5.2.8 on 2026-02-14 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_rangeentry_service_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDepotRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('qty_mt', models.FloatField()),
                ('km', models.FloatField()),
                ('mt_km', models.FloatField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
                ('depot_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='erp.transportdepotsection')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.destination')),
                ('range_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='erp.rangeentry')),
            ],
        ),
    ]
