# Generated by Django 5.2.8 on 2026-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_transportdepotrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingbillsection',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
